const FilterActionTypes = {
  FETCH_FILTERS_START: 'FETCH_FILTERS_START',
  FETCH_FILTERS_SUCCESS: 'FETCH_FILTERS_SUCCESS',
  FETCH_FILTERS_FAILURE: 'FETCH_FILTERS_FAILURE'
};

export default FilterActionTypes;