const FilterActionTypes = {
  FETCH_DONATION_TYPES_START: 'FETCH_DONATION_TYPES_START',
  FETCH_DONATION_TYPES_SUCCESS: 'FETCH_DONATION_TYPES_SUCCESS',
  FETCH_DONATION_TYPES_FAILURE: 'FETCH_DONATION_TYPES_FAILURE'
};

export default FilterActionTypes;