const FilterActionTypes = {
  INVERT_FILTER_IS_APPLIED: 'INVERT_FILTER_IS_APPLIED',
  CLEAR_ALL_SELECTED_FILTERS: 'CLEAR_ALL_SELECTED_FILTERS',
  FETCH_FILTERS_START: 'FETCH_FILTERS_START',
  FETCH_FILTERS_SUCCESS: 'FETCH_FILTERS_SUCCESS',
  FETCH_FILTERS_FAILURE: 'FETCH_FILTERS_FAILURE'
};

export default FilterActionTypes;