const OrganizationActionTypes = {
  FETCH_CENTERS_START: 'FETCH_CENTERS_START',
  FETCH_CENTERS_SUCCESS: 'FETCH_CENTERS_SUCCESS',
  FETCH_CENTERS_FAILURE: 'FETCH_CENTERS_FAILURE'
};

export default OrganizationActionTypes;